import { boolean, date, integer, jsonb, numeric, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import type { Availability, BoardTheme, ExplanationStyle, LearnerLevel } from "@usavvy/shared-types";

/**
 * IDs are UUIDv7 (Consistency Conventions) — generated by Postgres 18's native
 * uuidv7() rather than in application code (verified live against the running
 * container before relying on it here).
 */
const uuidv7Default = sql`uuidv7()`;

export const users = pgTable("users", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  email: text("email").notNull().unique(),
  // Null for Google-only accounts (AC #2) — never set for those rows.
  passwordHash: text("password_hash"),
  // Null until a learner links/creates via Google OAuth.
  googleId: text("google_id").unique(),
  role: text("role").notNull().default("student"),
  // Story 1.5 (FR-A-5): null means "never set" — the response layer falls back to the
  // email's local-part (getMe/updateDisplayName), the same "derive, don't snapshot"
  // philosophy deriveAgeFields already uses, so a future fallback-rule change needs no
  // backfill migration.
  displayName: text("display_name"),
  // Story 1.7 (FR-A-7): both null until a deletion is requested. Actual purge (the
  // cross-service data removal, and the 30-day-later execution itself) is deferred —
  // no JobQueuePort exists yet to schedule it, and no service exists yet to subscribe
  // to the user.deletion_requested event this story publishes.
  deletionRequestedAt: timestamp("deletion_requested_at", { withTimezone: true }),
  scheduledDeletionAt: timestamp("scheduled_deletion_at", { withTimezone: true }),
  // Null until the account is verified (signup) or immediately set (Google OAuth, AC #2).
  emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }),
  // Single active refresh token per user (MVP scope — no multi-device session list).
  // Stores only its hash, rotated on every /auth/refresh use.
  refreshTokenHash: text("refresh_token_hash"),
  // Story 1.2 (FR-A-2/NFR-16): null means "not yet declared". String mode ("YYYY-MM-DD")
  // matches the wire format end to end with no Date-object conversion layer.
  birthdate: date("birthdate", { mode: "string" }),
  // Only ever set when the declared age is under 18 — never the learner's own email.
  parentEmail: text("parent_email"),
  // Null means pending (or not-applicable for an adult) — set once the parent clicks
  // the consent link.
  parentConsentedAt: timestamp("parent_consented_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  // Optimistic-concurrency column per Consistency Conventions.
  version: integer("version").notNull().default(1),
});

export const emailVerificationTokens = pgTable("email_verification_tokens", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  // Only the SHA-256 hash of the raw token is stored — the raw token is emailed once
  // and never persisted, same hygiene already applied to the refresh token.
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Story 1.2: structurally identical to emailVerificationTokens — same hygiene (only
// the token hash is persisted), sent to parentEmail rather than the learner's own.
export const parentalConsentTokens = pgTable("parental_consent_tokens", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  userId: uuid("user_id")
    .notNull()
    .references(() => users.id),
  tokenHash: text("token_hash").notNull().unique(),
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
  usedAt: timestamp("used_at", { withTimezone: true }),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Story 1.3 (FR-A-3): the first core-owned entity beyond users/tokens — named in the
// architecture's own AD-14 ownership table under `core`, schema'd here for the first
// time. One row per user (see the unique index below); all fields null until their
// corresponding wizard step is saved, except currentStep/version which always exist.
export const learnerProfiles = pgTable("learner_profiles", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  userId: uuid("user_id")
    .notNull()
    .unique()
    .references(() => users.id),
  goal: text("goal"),
  interests: text("interests").array(),
  availability: jsonb("availability").$type<Availability>(),
  sessionLengthMinutes: integer("session_length_minutes"),
  targetCompletionDate: date("target_completion_date", { mode: "string" }),
  level: text("level").$type<LearnerLevel>(),
  // Forward-only progress pointer — an index into ONBOARDING_STEPS (shared-types).
  // Never regresses, even when an earlier step is edited after later ones are done.
  currentStep: integer("current_step").notNull().default(0),
  // Null until currentStep reaches ONBOARDING_STEPS.length (independent of whether
  // targetCompletionDate itself has a value — it's the one step allowed to be skipped).
  completedAt: timestamp("completed_at", { withTimezone: true }),
  // Story 1.4 (FR-A-4): all 6 nullable, not defaulted at the DB level — defaults are
  // computed at the service layer (DEFAULT_LEARNER_PREFERENCES), the same
  // "derive, don't snapshot" philosophy deriveAgeFields/getMe already use. Unlike the
  // onboarding fields above, these have no "not yet answered" meaning to preserve —
  // null here just means "hasn't overridden the default yet."
  voiceEnabled: boolean("voice_enabled"),
  // Review finding: `real` (IEEE-754 float) round-trips 0.1-step values with rounding
  // artifacts (e.g. 1.2 becoming 1.2000000476837158). Fixed-point numeric(3,1) avoids
  // that entirely for a bounded 0.5–2.0 rate; `mode: "number"` keeps the JS-side type a
  // plain number rather than Postgres's default numeric-as-string.
  speechRate: numeric("speech_rate", { precision: 3, scale: 1, mode: "number" }),
  boardTheme: text("board_theme").$type<BoardTheme>(),
  explanationStyle: text("explanation_style").$type<ExplanationStyle>(),
  captionsEnabled: boolean("captions_enabled"),
  reducedMotion: boolean("reduced_motion"),
  // Story 1.6 (FR-A-6): same nullable-not-defaulted-at-the-DB-level convention as the
  // preference columns above — defaults are FR-A-6's own literal values, computed at
  // the service layer via DEFAULT_PRIVACY_SETTINGS.
  publicLeaderboardSharing: boolean("public_leaderboard_sharing"),
  cohortDisplayName: boolean("cohort_display_name"),
  uploadsForTraining: boolean("uploads_for_training"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  version: integer("version").notNull().default(1),
});
