import { integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";

// Story 3.1 (FR-B-1). Same uuidv7() default every other service's tables use
// (Consistency Conventions).
const uuidv7Default = sql`uuidv7()`;

// Story 3.1 (FR-B-1), AD-14. This service's first entity — the live teaching-run state
// machine (AD-10: `LearningSession`, never the bare PRD term `Session`). `userId`/
// `conceptId` are bare, opaque, non-FK cross-service ids (AD-13/AD-14 — `User` is owned
// by core, `Concept` by courses; neither is ever a real FK from here).
export const learningSessions = pgTable(
  "learning_sessions",
  {
    id: uuid("id").primaryKey().default(uuidv7Default),
    userId: text("user_id").notNull(),
    conceptId: text("concept_id").notNull(),
    // "active" | "paused" | "ended" — a plain text column, matching this codebase's
    // existing status-column convention (no DB enum anywhere in this codebase).
    status: text("status").notNull().default("active"),
    // Nullable: null only for the brief window between a session being created and its
    // first Beat being set as current — in practice always set immediately by
    // createOrResumeLearningSession. A real FK is fine here since Beat is also owned by
    // this same service (AD-14 only forbids a cross-service FK).
    currentBeatId: uuid("current_beat_id"),
    // AC #1's paused-state fields — null until the first Pause. `boardRenderState` is an
    // opaque blob this service stores/returns verbatim and never interprets (its shape is
    // the frontend's concern, not this service's) — same "opaque jsonb passthrough"
    // convention as `checkpointQuestions`/`availability` elsewhere in this codebase.
    narrationOffsetMs: integer("narration_offset_ms"),
    boardRenderState: jsonb("board_render_state").$type<Record<string, unknown>>(),
    startedAt: timestamp("started_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  // Code-review finding: createOrResumeLearningSession's idempotent lookup was only
  // enforced in application code — two concurrent create calls for the same
  // (userId, conceptId) could both miss each other and insert duplicate active
  // sessions. A partial unique index enforces "at most one non-ended session per
  // (userId, conceptId)" at the DB level; ended sessions are excluded so a learner can
  // freely start a fresh session for a concept they've already completed (relearning).
  (table) => [uniqueIndex("learning_sessions_user_concept_active_idx").on(table.userId, table.conceptId).where(sql`status <> 'ended'`)],
);

// Story 3.1 (FR-B-1), AD-14. PRD §14's exact minimal field list (`narration`,
// `board_action`, `audio_ref`, `source_ref`) — caller-supplied at session-creation time,
// not generated by this story (real Beat content generation is GenerationPort's future
// job, Stories 3.5+/3.14+ — see this story's CRITICAL SCOPE NOTE).
export const beats = pgTable("beats", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  sessionId: uuid("session_id")
    .notNull()
    .references(() => learningSessions.id, { onDelete: "cascade" }),
  // Ordering within the session — the position/order-column tiebreaker convention
  // (ORDER BY position, id) applies wherever this is queried.
  position: integer("position").notNull(),
  narration: text("narration").notNull(),
  // PRD §10.1's typed board-action instruction (write | draw | highlight | step |
  // diagram | code | equation) — an opaque blob, not enumerated at the DB layer since no
  // story yet defines the full instruction shape (Stories 3.5-3.10's job).
  boardAction: jsonb("board_action").notNull().$type<Record<string, unknown>>(),
  audioRef: text("audio_ref"),
  sourceRef: text("source_ref"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

// Story 3.1 (FR-B-1), AD-14/AD-18. The append-only lifecycle log Activity History will
// eventually read directly (AD-18) — this story only needs to write it correctly, not
// build that read path (see Story 1.11's own Dev Notes, already confirming this).
export const sessionEvents = pgTable("session_events", {
  id: uuid("id").primaryKey().default(uuidv7Default),
  sessionId: uuid("session_id")
    .notNull()
    .references(() => learningSessions.id, { onDelete: "cascade" }),
  // Past-tense per the Consistency Conventions' domain-event naming rule, e.g.
  // "started"/"paused"/"resumed"/"ended" — a plain text column, not a DB enum.
  type: text("type").notNull(),
  payload: jsonb("payload").$type<Record<string, unknown>>(),
  occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
});
